export const staticProductContent: Record<string, { title: string; content: string }> = {
  // This content is now generated by AI on-demand when a user adds a product to the cart.
  // The content is stored in localStorage and retrieved by the /download-pdf/[id] page.
  // This object is kept to avoid breaking imports, but it is no longer used for content.
};
