'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useUser } from '@/firebase/auth/use-user';
import { firestore } from '@/firebase/client';
import { collection, onSnapshot, query, orderBy, Timestamp } from 'firebase/firestore';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Skeleton } from '@/components/ui/skeleton';
import { formatDistanceToNow } from 'date-fns';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';
import { FileText } from 'lucide-react';
import type { GeneratedContent } from '@/lib/types';

export default function GeneratedPdfsPage() {
  const { user } = useUser();
  const router = useRouter();
  const [generatedPdfs, setGeneratedPdfs] = useState<GeneratedContent[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user && user.email !== 'the.designer.crevva@gmail.com') {
      router.push('/dashboard');
    }
  }, [user, router]);

  useEffect(() => {
    if (user && user.email === 'the.designer.crevva@gmail.com' && firestore) {
      const pdfsQuery = query(collection(firestore, 'generated_content'), orderBy('createdAt', 'desc'));
      
      const unsubscribe = onSnapshot(pdfsQuery, (snapshot) => {
        const fetchedPdfs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as GeneratedContent));
        setGeneratedPdfs(fetchedPdfs);
        setLoading(false);
      }, (error) => {
        const permissionError = new FirestorePermissionError({
          path: collection(firestore, 'generated_content').path,
          operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
        setLoading(false);
      });

      return () => unsubscribe();
    } else if (user) {
        setLoading(false);
    }
  }, [user]);
  
  if (loading) {
    return (
        <div className="container mx-auto px-4 py-8">
            <h1 className="text-3xl font-bold mb-8">Generated Documents</h1>
            <Card>
                <CardHeader>
                    <Skeleton className="h-8 w-48" />
                    <Skeleton className="h-4 w-80" />
                </CardHeader>
                <CardContent>
                    <div className="space-y-4">
                        <Skeleton className="h-12 w-full" />
                        <Skeleton className="h-12 w-full" />
                        <Skeleton className="h-12 w-full" />
                    </div>
                </CardContent>
            </Card>
        </div>
    );
  }

  if (user?.email !== 'the.designer.crevva@gmail.com') {
      return (
          <div className="container mx-auto px-4 py-8 text-center">
              <h1 className="text-3xl font-bold mb-4">Access Denied</h1>
              <p>You do not have permission to view this page.</p>
          </div>
      )
  }

  return (
    <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-8">Generated Documents</h1>
        <Card>
            <CardHeader>
                <CardTitle>AI-Generated Content</CardTitle>
                <CardDescription>
                    {generatedPdfs.length} documents have been generated by the background AI process.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Document Title</TableHead>
                            <TableHead className="text-right">Generated</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {generatedPdfs.length > 0 ? (
                            generatedPdfs.map(pdf => (
                                <TableRow key={pdf.id}>
                                    <TableCell>
                                        <div className="flex items-center gap-3">
                                            <FileText className="h-5 w-5 text-muted-foreground" />
                                            <div className="font-medium">{pdf.title}</div>
                                        </div>
                                    </TableCell>
                                    <TableCell className="text-right">
                                        {pdf.createdAt ? formatDistanceToNow(pdf.createdAt.toDate(), { addSuffix: true }) : ''}
                                    </TableCell>
                                </TableRow>
                            ))
                        ) : (
                            <TableRow>
                                <TableCell colSpan={2} className="h-24 text-center">
                                    No documents generated yet.
                                </TableCell>
                            </TableRow>
                        )}
                    </TableBody>
                </Table>
            </CardContent>
        </Card>
    </div>
  )
}
