'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useState, useEffect } from 'react';

export default function TermsOfServicePage() {
  const [currentDate, setCurrentDate] = useState('');

  useEffect(() => {
    setCurrentDate(new Date().toLocaleDateString());
  }, []);

  return (
    <div className="container mx-auto px-4 py-8 md:py-12 min-h-[calc(100vh-14rem)]">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tighter mb-8 text-center">Terms of Service</h1>
        <Card>
          <CardHeader>
            <CardTitle>Welcome to Eleven Docs</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-invert max-w-none">
            <p>Last updated: {currentDate}</p>
            
            <h2>1. Introduction</h2>
            <p>
              Welcome to Eleven Docs! These Terms of Service ("Terms") govern your use of our website (the "Service") and form a binding contractual agreement between you, the user of the Service, and us.
            </p>

            <h2>2. Acceptance of Terms</h2>
            <p>
              By creating an account, purchasing products, or otherwise using our Service, you agree to be bound by these Terms. If you do not agree to these Terms, you must not access or use the Service.
            </p>

            <h2>3. Use of the Service</h2>
            <p>
              You agree to use the Service only for purposes that are permitted by these Terms and any applicable law, regulation, or generally accepted practices or guidelines in the relevant jurisdictions.
            </p>
            <p>
              You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer.
            </p>

            <h2>4. Digital Products</h2>
            <p>
              All products sold on Eleven Docs are digital. Due to the nature of digital products, all sales are final and non-refundable. When you purchase a product, you are granted a non-exclusive, non-transferable license to use the product for personal or professional use, as specified in the product description.
            </p>
            <p>
              You may not resell, redistribute, or share the digital products you purchase.
            </p>

            <h2>5. AI PDF Generator</h2>
            <p>
              Our AI PDF Generator service allows you to create documents based on your prompts. You are responsible for the prompts you provide. You may not use the service to generate content that is illegal, harmful, or infringes on the rights of others.
            </p>
            <p>
              The content generated by the AI is for your use. We do not claim ownership of the content you create. However, we grant you a license to use the generated content upon successful payment.
            </p>

            <h2>6. Intellectual Property</h2>
            <p>
              The Service and its original content (excluding content created by users), features, and functionality are and will remain the exclusive property of Eleven Docs and its licensors.
            </p>

            <h2>7. Termination</h2>
            <p>
              We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
            </p>

            <h2>8. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
            </p>

            <h2>9. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at the.designer.crevva@gmail.com.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
